config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  get 'main/index'

  get 'main/brand/:brand_id', to: 'main#brand'

  get 'main/search'

  get 'main/detail/:item_id', to: 'main#detail'

  resources :items
  resources :brands
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items, :dependent => :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :brand

  def wrapped_image
    wrap_image = "https://placehold.it/170x170"
    if main_image != nil && main_image.length > 0
      wrap_image = main_image
    end
    return wrap_image
  end

  def formatted_price
    if price != nil && price.integer?
      return price.to_s(:delimited)
    else
      return '---'
    end
  end

  def wrapped_title
    if overwritten_title != nil && overwritten_title.length > 0
      return overwritten_title
    end
    return title
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  http_basic_authenticate_with name: ENV['BASIC_AUTH_NAME'], password: ENV['BASIC_AUTH_PASS'] if Rails.env.production?
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:name, :description)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  http_basic_authenticate_with name: ENV['BASIC_AUTH_NAME'], password: ENV['BASIC_AUTH_PASS'] if Rails.env.production?
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @search_brand_name = params[:brand_name]
    @search_item_title = params[:item_title]
    @search_item_active = params[:item_active]
    @items = Item.all
    if @search_brand_name != nil && @search_brand_name.length > 0
      @items = @items.where(:brand => Brand.where('lower(name) = ?', @search_brand_name.downcase).first)
    end
    if @search_item_title != nil && @search_item_title.length > 0
      @items = @items.where("lower(title) like '%#{@search_item_title.downcase}%'")
    end
    if @search_item_active != nil && @search_item_active.length > 0
      @items = @items.where(:active => @search_item_active)
    end
    @items = @items.page(params[:page])
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:asin, :title, :description, :price, :amazon_url, :brand_id, :group, :main_image, :stocks, :active, :overwritten_title)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @brands = Brand.all
    @html_meta_desription = "「ブランド物iPhoneケース」は、ブランド物のiPhoneケースを紹介するサイトです。";
  end

  def brand
    brand = Brand.find(params[:brand_id])
    @header = 'ブランド'
    @subheader = brand.name
    @list_description = brand.description
    @items = brand.items.where(:active => 1).order("price desc").page(params[:page])
    @html_title = @subheader + " | "
    @html_meta_desription = "「" + brand.name + "」のiphoneケースを紹介します。"
    render :template => 'main/list'
  end

  def search
  end

  def detail
    @item = Item.find(params[:item_id])
    @header = @item.brand.name
    @subheader = @item.wrapped_title
    @html_title = @subheader + " | "
    @html_meta_desription = "「" + @item.ec_site + "」 の「ストア：" + @item.group + "」が販売する 「" + @item.brand.name + "」 のiPhoneケース." 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_brands
    Brand.joins(:items).where("items.active = 1").group("brands.id").having("count(items.id) > ?", 0)
  end

  def default_image
    "https://placehold.it/170x170"
  end

  def site_name
    "ブランド物iPhoneケース"
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/brands/_form.html.erb
<%= form_with(model: brand, local: true) do |form| %>
  <% if brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :name, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.text_field :name, id: :brand_name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :description, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.text_area :description, id: :brand_description, class: "form-control" %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit :class => "btn btn-lg btn-secondary btn-block" %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<div class="container">
  <h1>Editing Brand</h1>

  <%= render 'form', brand: @brand %>

  <%= link_to 'Show', @brand, class: "btn btn-primary" %> |
  <%= link_to 'Back', brands_path, class: "btn btn-primary" %>
  </br>
  </br>
  </br>
  <%= link_to 'Destroy', @item, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
</div>

app/views/brands/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Brands</h1>

  <table class="table table-bordered">
    <thead class="thead-default">
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @brands.each do |brand| %>
        <tr>
          <td><%= brand.name %></td>
          <td><%= link_to 'Show', brand, class: "btn btn-primary" %></td>
          <td><%= link_to 'Edit', edit_brand_path(brand), class: "btn btn-primary" %></td>
          <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Brand', new_brand_path, class: "btn btn-success" %>
</div>

app/views/brands/new.html.erb
<div class="container">
<h1>New Brand</h1>

<%= render 'form', brand: @brand, class: "btn btn-primary" %>

<%= link_to 'Back', brands_path, class: "btn btn-primary" %>
</div>

app/views/brands/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
  <strong>Name:</strong>
  <%= @brand.name %>
  </p>

  <p>
  <strong>Description:</strong>
  <%= @brand.description %>
  </p>

  <%= link_to 'Edit', edit_brand_path(@brand), class: "btn btn-primary" %> |
  <%= link_to 'Back', brands_path, class: "btn btn-primary" %>
</div>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :asin, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.text_field :asin, id: :item_asin, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :title, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.text_area :title, id: :item_title, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :overwritten_title, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.text_area :overwritten_title, id: :item_overwritten_title, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :description, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.text_area :description, id: :item_description, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :price, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.number_field :price, id: :item_price, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :amazon_url, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.text_area :amazon_url, id: :item_amazon_url, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :brand_id, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.select :brand_id, Brand.all.map { |b| [b.name, b.id] }, {}, {id: "item_brand_id", class: "form-control"} %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :group, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.text_field :group, id: :item_group, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :main_image, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.text_area :main_image, id: :item_main_image, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :stocks, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.number_field :stocks, id: :item_stocks, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :active, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.number_field :active, id: :item_active, class: "form-control" %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit :class => "btn btn-lg btn-secondary btn-block" %>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="container">
  <h1>Editing Item</h1>

  <%= render 'form', item: @item %>

  <%= link_to 'Show', @item %> |
  <%= link_to 'Back', items_path %>
  </br>
  </br>
  </br>
  <%= link_to 'Destroy', @item, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
</div>

app/views/items/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1>Items</h1>

  <div class="row">
    <div class="col-sm-12">
      <form action="/items">
        <input type="text" name="brand_name" placeholder="Brand.name" value="<%= @search_brand_name %>" />
        <input type="text" name="item_title" placeholder="Title" value="<%= @search_item_title %>" />
        <input type="number" name="item_active" placeholder="Active[-1, 0, 1]" value="<%= @search_item_active %>"/>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
  </div>
  <table class="table table-bordered">
    <thead class="thead-default">
      <tr>
        <th>#</th>
        <th>Asin</th>
        <th>Title</th>
        <th>Brand</th>
        <th>Main image</th>
        <th>Active</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= item.asin %></td>
          <td><%= link_to item.title.truncate(50), item.amazon_url %></td>
          <td><%= item.brand.name %></td>
          <td>
            <% begin %>
              <%= image_tag item.wrapped_image, :height => 100 %>
            <% rescue => ex %>
              <%= image_tag default_image, :height => 100 %>
            <% end %>
          </td>
          <td><%= item.active %></td>
          <td><%= link_to 'Show', item, class: "btn btn-primary" %></td>
          <td><%= link_to 'Edit', edit_item_path(item), class: "btn btn-primary" %></td>
          <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <!-- Pagination -->
  <ul class="pagination justify-content-center">
    <%= paginate @items %>
  </ul>

  <br>

  <%= link_to 'New Item', new_item_path, class: "btn btn-success" %>
</div>

app/views/items/new.html.erb
<div class="container">
  <h1>New Item</h1>

  <%= render 'form', item: @item %>

  <%= link_to 'Back', items_path %>
</div>

app/views/items/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
  <strong>Asin:</strong>
  <%= @item.asin %>
  </p>

  <p>
  <strong>Title:</strong></br>
  <%= link_to @item.title, @item.amazon_url  %>
  </p>

  <p>
  <strong>Overwritten title:</strong></br>
  <%= @item.overwritten_title %>
  </p>

  <p>
  <strong>Description:</strong></br>
  <%= @item.description %>
  </p>

  <p>
  <strong>Price:</strong>
  <%= @item.price %>
  </p>

  <p>
  <strong>Brand:</strong>
  <%= @item.brand.name %>
  </p>

  <p>
  <strong>Group:</strong>
  <%= @item.group %>
  </p>

  <p>
  <strong>Main image:</strong>
  <% begin %>
    <%= image_tag @item.wrapped_image %>
  <% rescue => ex %>
    <%= image_tag default_image %>
  <% end %>
  </p>

  <p>
  <strong>Stocks:</strong>
  <%= @item.stocks %>
  </p>

  <p>
  <strong>Active:</strong>
  <%= @item.active %>
  </p>

  <%= link_to 'Edit', edit_item_path(@item) %> |
  <%= link_to 'Back', items_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @html_title %><%= site_name %></title>
    <%= favicon_link_tag() %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="description" content="<%= @html_meta_desription %>" />
  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <%= link_to site_name, root_path, {:class => "navbar-brand"} %>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Brands
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
                <% active_brands.each do |brand| %>
                  <%= link_to brand.name, {controller: "main", action: "brand", brand_id: brand.id}, {:class => "dropdown-item"} %>
                <% end %>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; <%= site_name %> 2017</p>
      </div>
      <!-- /.container -->
    </footer>
  </body>
</html>

app/views/main/brand.html.erb
<h1>Main#brand</h1>
<p>Find me in app/views/main/brand.html.erb</p>

app/views/main/detail.html.erb
<!-- Page Content -->
<div class="container">

  <!-- Page Heading/Breadcrumbs -->
  <h1 class="mt-4 mb-3">
    <small><%= @subheader %></small>
  </h1>

  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to 'Home', root_path %>
    </li>
    <li class="breadcrumb-item">
      <%= link_to @header, controller: "main", action: "brand", brand_id: @item.brand.id %>
    </li>
    <li class="breadcrumb-item active">商品詳細</li>
  </ol>

  <!-- Portfolio Item Row -->
  <div class="row">

    <div class="col-md-6">
      <% begin %>
        <%= image_tag(@item.wrapped_image, :class => "card-img-top") %>
      <% rescue => ex %>
        <%= image_tag(default_image, :class => "card-img-top") %>
      <% end %>
    </div>

    <div class="col-md-6">
      <h3 class="my-3">商品名</h3>
      <p><%= @item.title %></p>
      <h3 class="my-3">説明</h3>
      <p><%= @html_meta_desription %></p>
      <h3 class="my-3">値段</h3>
      <p><%= @item.formatted_price %>円</p>

      <!-- Call to Action Section -->
      <a class="btn btn-lg btn-secondary btn-block" href="<%= @item.amazon_url %>" target="_blank">もっと見る</a>
    </div>

  </div>
  <!-- /.row -->

</div>
<!-- /.container -->

app/views/main/index.html.erb
<header>
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <!-- Slide One - Set the background image for this slide in the line below -->
      <div class="carousel-item active" style="background-image: url('<%= asset_path 'famous_items.jpg' %>')">
        <div class="carousel-caption d-none d-md-block">
          <!-- <h3>人気のアイテム</h3> -->
          <!-- <p>This is a description for the first slide.</p> -->
        </div>
      </div>
      <!-- Slide Two - Set the background image for this slide in the line below -->
      <div class="carousel-item" style="background-image: url('<%= asset_path 'new_items.jpg' %>')">
        <div class="carousel-caption d-none d-md-block">
          <!-- <h3>新着アイテム</h3> -->
          <!-- <p>This is a description for the first slide.</p> -->
        </div>
      </div>
      <!-- Slide Three - Set the background image for this slide in the line below -->
      <div class="carousel-item" style="background-image: url('<%= asset_path 'rare_items.jpg' %>')">
        <div class="carousel-caption d-none d-md-block">
          <!-- <h3>特徴的なアイテム</h3> -->
          <!-- <p>This is a description for the first slide.</p> -->
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</header>

<div class="container">

  <!-- Portfolio Section -->
  <h1 class="my-4">「<%= site_name %>」へようこそ！</h1>
  <p>
  「<%= site_name %>」は、ブランド物のiPhoneケースを紹介するサイトです。
  </p>

  <h2>人気のブランド</h2>

  <div class="row">
    <% active_brands.each do |brand| %>
      <div class="col-lg-4 portfolio-item">
        <div class="card h-100 portfolio-item-body">
          <% begin %>
            <%= link_to image_tag(brand.items.where(:active => 1).order("price desc").first.wrapped_image, :class => "card-img-top portfolio-item-img"), controller: "main", action: "brand", brand_id: brand.id %>
          <% rescue => ex %>
            <%= link_to image_tag(default_image, :class => "card-img-top portfolio-item-img"), controller: "main", action: "brand", brand_id: brand.id %>
          <% end %> 
          <div class="card-body">
            <h4 class="card-title">
              <%= link_to brand.name, controller: "main", action: "brand", brand_id: brand.id %>
            </h4>
            <p class="card-text">
              <% if brand.description != nil %>
                <%= brand.description.truncate(60) %>
              <% end %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <!-- /.row -->

</div>
<!-- /.container -->

app/views/main/list.html.erb
<!-- Page Content -->
<div class="container">

  <!-- Page Heading/Breadcrumbs -->
  <h1 class="mt-4 mb-3"><%= @header %>:
    <small><%= @subheader %></small>
  </h1>

  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to 'Home', root_path %>
    </li>
    <li class="breadcrumb-item active"><%= @subheader %></li>
  </ol>

  <p> <%= @list_description %> </p>

  <div class="row">
    <% @items.each do |item| %>
      <div class="col-lg-4 portfolio-item">
        <div class="card h-100 portfolio-item-body">
          <div class="card-header"><%= item.ec_site %></div>
          <% begin %>
            <%= link_to image_tag(item.wrapped_image, :class => "card-img-top portfolio-item-img"), controller: "main", action: "detail", item_id: item.id %>
          <% rescue => ex %>
            <%= link_to image_tag(default_image, :class => "card-img-top portfolio-item-img"), controller: "main", action: "detail", item_id: item.id %>
          <% end %>
          <div class="card-body">
            <h4 class="card-title">
              <%= link_to item.wrapped_title.truncate(30), controller: "main", action: "detail", item_id: item.id %>
            </h4>
            <h5><%= item.formatted_price %>円</h5>
            <p class="card-text"><%= item.description.truncate(120) %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <!-- Pagination -->
  <ul class="pagination justify-content-center">
    <%= paginate @items %>
  </ul>

</div>
<!-- /.container -->

app/views/main/search.html.erb
<h1>Main#search</h1>
<p>Find me in app/views/main/search.html.erb</p>